### ISSUE TITLE
"No spool selected" when starting a print

### ISSUE THREAD

**Issue by DanielChydz** [mdziekon/OctoPrint-SpoolManager#48]
Opening the issue here again since original repo appears to be no longer maintained. [The issue has been known for years.](https://github.com/OllisGit/OctoPrint-SpoolManager/issues/218) Please, fix it.

![image](https://github.com/OllisGit/OctoPrint-SpoolManager/assets/83183534/28e41f7c-cdf3-43b2-b321-2f79787d6d1a)

octoprint.log

```
2023-09-18 18:26:59,729 - octoprint.plugins.SpoolManager - INFO - Send Event 'plugin_spoolmanager_spool_selected' with payload '{'toolId': 0, 'databaseId': 5, 'spoolName': 'Black 4', 'material': 'PLA', 'colorName': 'black', 'remainingWeight': 29.11168592375251}' to event-bus
2023-09-18 18:26:59,732 - octoprint.plugins.SpoolManager - INFO - Send Event 'plugin_spoolmanager_spool_selected' with payload '{'toolId': 0, 'databaseId': 5, 'spoolName': 'Black 4', 'material': 'PLA', 'colorName': 'black', 'remainingWeight': 29.11168592375251}' to event-bus
2023-09-18 18:27:04,582 - octoprint.plugins.SpoolManager - INFO - Send Event 'plugin_spoolmanager_spool_selected' with payload '{'toolId': 0, 'databaseId': 5, 'spoolName': 'Black 4', 'material': 'PLA', 'colorName': 'black', 'remainingWeight': 29.11168592375251}' to event-bus
2023-09-18 18:27:04,585 - octoprint.plugins.SpoolManager - INFO - Send Event 'plugin_spoolmanager_spool_selected' with payload '{'toolId': 0, 'databaseId': 5, 'spoolName': 'Black 4', 'material': 'PLA', 'colorName': 'black', 'remainingWeight': 29.11168592375251}' to event-bus
2023-09-18 18:27:08,055 - octoprint.plugins.SpoolManager - DEBUG - API Load all spool
2023-09-18 18:27:08,063 - octoprint.plugins.SpoolManager - INFO - Send Event 'plugin_spoolmanager_spool_selected' with payload '{'toolId': 0, 'databaseId': 5, 'spoolName': 'Black 4', 'material': 'PLA', 'colorName': 'black', 'remainingWeight': 29.11168592375251}' to event-bus
```
SpoolManager 1.7.0
OctoPrint 1.9.2
Hosted on Windows 10

Option below does not resolve the issue
![image](https://github.com/OllisGit/OctoPrint-SpoolManager/assets/83183534/ba314a43-c42b-47d1-ac0d-4fff3756be02)

**Comment by flaviut** [comment]
In my case, the problem is that the Octoprint analysis incorrectly determined the print contained no extrusion: "Model contains no extrusion."

![image](https://github.com/mdziekon/OctoPrint-SpoolManager/assets/5213469/6c0b1465-3e49-40db-a2de-2004cc859608)

This was then in turn caused by an error in the analysis code, which was caused by a change in Python 3.11 and the PrintTimeGenius plugin: 

```
2023-11-05 11:33:21,133 - octoprint.printer.standard - ERROR - Error while pausing the analysis queue
Traceback (most recent call last):
  File "/opt/octoprint/lib/python3.11/site-packages/octoprint/printer/standard.py", line 1482, in on_comm_state_change
    self._analysisQueue.pause()  # only analyse files while idle
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/octoprint/lib/python3.11/site-packages/octoprint/filemanager/analysis.py", line 129, in pause
    q.pause()
  File "/opt/octoprint/lib/python3.11/site-packages/octoprint/filemanager/analysis.py", line 265, in pause
    self._do_abort()
  File "/opt/octoprint/lib/python3.11/site-packages/octoprint_PrintTimeGenius/__init__.py", line 207, in _do_abort
    if _allow_analysis(self._plugin._printer, self._plugin._settings):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/octoprint/lib/python3.11/site-packages/octoprint_PrintTimeGenius/__init__.py", line 186, in _allow_analysis
    if not isinstance(thermostat, collections.Mapping) or not 'actual' in thermostat or not 'target' in thermostat or thermostat['target'] is None:
                                  ^^^^^^^^^^^^^^^^^^^
AttributeError: module 'collections' has no attribute 'Mapping'
```

---

- https://github.com/eyal0/OctoPrint-PrintTimeGenius/issues/311
- https://github.com/eyal0/OctoPrint-PrintTimeGenius/pull/312

**Comment by Letme** [comment]
Here is how I reach this (or similar) issue:

You do print 1, select spools and start the print. Once print completes (failure or not), you select print 2, spools below in UI remain the same, but when you click Print, it tells you Tool 0 and Tool 1 are not selected. Sometimes you delete selection of 1 spool and reselect the same spool from lets say Tool 0 and you can print (both Tools then have spools - no warning), but other times I need to delete both spools and reselect them.

**Comment by thegreekgeek** [comment]
Just dropping in to say that I'm getting something similar when I try to print a continuous print .gjob file, the plugin freaks out and says there's no metadata associated with the file and the required filament is unknown.

**Comment by icariantk** [comment]
But to avoid stale, same problem here.

**Comment by mfr69bs** [comment]
Same problem here:
`Required Filament unknown
Ungefähre Dauer: -
Kosten: no filament from meta`

`ATTENTION: Needed filament could not calculated (missing metadata or spool-fields)
There is no spool selected for Tool 0 despite it being used (maybe) by this print.
Do you want to start the print without a selected spool?`

SpoolManager 1.7.3
OctoPrint 1.10.2 (based on OctoPi 1.0.0 (build 2024.06.18.085851)
Python 3.9.2
